name: Publish core

on:
  push:
    branches:
      - 'actions'
    paths:
      - 'app/scripts/modules/core/package.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.15.1
        uses: actions/setup-node@v1
        with:
          node-version: 10.15.1
      - name: publish amazon
        run: |
          yarn install
          echo "This action was kicked off against the sha: ${GITHUB_SHA}"
          app/scripts/modules/github_actions_publish.sh amazon
        env:
          CI: true
