name: Publish packages

on:
  push:
    branches:
      - 'actions'
    paths:
      - 'app/scripts/modules/**/package.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.15.1
        uses: actions/setup-node@v1
        with:
          node-version: 10.15.1
      - name: yarn install, publish
        run: |
          yarn install
          yarn publish
        env:
          CI: true
